package ffmpeg_test

import (
	"bytes"
	"errors"
	"io"
	"os"
	"path/filepath"
	"testing"

	ffmpeg "github.com/linuxmatters/ffmpeg-statigo"
)

// fixtureBytes synthesises a small valid video-only file with the built-in,
// licence-clean mpeg2video encoder and returns its raw bytes. It uses only the
// public bindings (no inline cgo), so it is safe to live in a _test.go file. The
// generated bytes feed the custom-AVIO demux below.
func fixtureBytes(t *testing.T) []byte {
	t.Helper()

	const (
		width   = 160
		height  = 120
		frames  = 12
		rateNum = 25
		rateDen = 1
	)

	dir := t.TempDir()
	path := filepath.Join(dir, "fixture.mp4")

	encoder := ffmpeg.AVCodecFindEncoder(ffmpeg.AVCodecIdMpeg2Video)
	if encoder == nil {
		t.Skip("mpeg2video encoder not built into static library")
	}

	encCtx := ffmpeg.AVCodecAllocContext3(encoder)
	if encCtx == nil {
		t.Fatal("alloc codec context failed")
	}
	defer ffmpeg.AVCodecFreeContext(&encCtx)

	encCtx.SetWidth(width)
	encCtx.SetHeight(height)
	encCtx.SetPixFmt(ffmpeg.AVPixFmtYuv420P)
	encCtx.SetTimeBase(ffmpeg.AVMakeQ(rateDen, rateNum))
	encCtx.SetFramerate(ffmpeg.AVMakeQ(rateNum, rateDen))
	encCtx.SetGopSize(10)
	encCtx.SetMaxBFrames(0)

	namePtr := ffmpeg.ToCStr(path)
	defer namePtr.Free()

	var ofmtCtx *ffmpeg.AVFormatContext
	if _, err := ffmpeg.AVFormatAllocOutputContext2(&ofmtCtx, nil, nil, namePtr); err != nil {
		t.Fatalf("alloc output context: %v", err)
	}
	defer ffmpeg.AVFormatFreeContext(ofmtCtx)

	if ofmtCtx.Oformat().Flags()&ffmpeg.AVFmtGlobalheader != 0 {
		encCtx.SetFlags(encCtx.Flags() | ffmpeg.AVCodecFlagGlobalHeader)
	}

	if _, err := ffmpeg.AVCodecOpen2(encCtx, encoder, nil); err != nil {
		t.Fatalf("open encoder: %v", err)
	}

	stream := ffmpeg.AVFormatNewStream(ofmtCtx, nil)
	if stream == nil {
		t.Fatal("new stream failed")
	}

	if _, err := ffmpeg.AVCodecParametersFromContext(stream.Codecpar(), encCtx); err != nil {
		t.Fatalf("copy codec params: %v", err)
	}
	stream.SetTimeBase(encCtx.TimeBase())

	if ofmtCtx.Oformat().Flags()&ffmpeg.AVFmtNofile == 0 {
		var pb *ffmpeg.AVIOContext
		if _, err := ffmpeg.AVIOOpen(&pb, namePtr, ffmpeg.AVIOFlagWrite); err != nil {
			t.Fatalf("open io: %v", err)
		}
		ofmtCtx.SetPb(pb)
	}

	if _, err := ffmpeg.AVFormatWriteHeader(ofmtCtx, nil); err != nil {
		t.Fatalf("write header: %v", err)
	}

	frame := ffmpeg.AVFrameAlloc()
	if frame == nil {
		t.Fatal("alloc frame failed")
	}
	defer ffmpeg.AVFrameFree(&frame)

	frame.SetWidth(width)
	frame.SetHeight(height)
	frame.SetFormat(int(ffmpeg.AVPixFmtYuv420P))

	if _, err := ffmpeg.AVFrameGetBuffer(frame, 0); err != nil {
		t.Fatalf("frame get buffer: %v", err)
	}

	pkt := ffmpeg.AVPacketAlloc()
	if pkt == nil {
		t.Fatal("alloc packet failed")
	}
	defer ffmpeg.AVPacketFree(&pkt)

	encode := func(f *ffmpeg.AVFrame) {
		if _, err := ffmpeg.AVCodecSendFrame(encCtx, f); err != nil {
			t.Fatalf("send frame: %v", err)
		}

		for {
			if _, err := ffmpeg.AVCodecReceivePacket(encCtx, pkt); err != nil {
				if errors.Is(err, ffmpeg.EAgain) || errors.Is(err, ffmpeg.AVErrorEOF) {
					return
				}
				t.Fatalf("receive packet: %v", err)
			}

			ffmpeg.AVPacketRescaleTs(pkt, encCtx.TimeBase(), stream.TimeBase())

			if _, err := ffmpeg.AVInterleavedWriteFrame(ofmtCtx, pkt); err != nil {
				ffmpeg.AVPacketUnref(pkt)
				t.Fatalf("write frame: %v", err)
			}

			ffmpeg.AVPacketUnref(pkt)
		}
	}

	for i := range frames {
		frame.SetPts(int64(i))
		encode(frame)
	}
	encode(nil)

	if _, err := ffmpeg.AVWriteTrailer(ofmtCtx); err != nil {
		t.Fatalf("write trailer: %v", err)
	}

	if ofmtCtx.Oformat().Flags()&ffmpeg.AVFmtNofile == 0 {
		if _, err := ffmpeg.AVIOClose(ofmtCtx.Pb()); err != nil {
			t.Fatalf("close io: %v", err)
		}
		ofmtCtx.SetPb(nil)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if len(data) == 0 {
		t.Fatal("fixture is empty")
	}

	return data
}

// TestAVIOAllocContextDemux feeds an in-memory byte buffer through a custom
// AVIOContext into an AVFormatContext, opens it, and reads at least one packet.
// Run with -race to confirm no data race and no C-side use-after-free; the
// deferred Close exercises handle deletion.
func TestAVIOAllocContextDemux(t *testing.T) {
	data := fixtureBytes(t)
	reader := bytes.NewReader(data)

	const bufSize = 4096

	avio := ffmpeg.AVIOAllocContext(bufSize, false,
		func(buf []byte) int {
			n, err := reader.Read(buf)
			if n == 0 && errors.Is(err, io.EOF) {
				return ffmpeg.AVErrorEofConst
			}
			return n
		},
		nil,
		func(offset int64, whence int) int64 {
			if whence&ffmpeg.AVSeekSize != 0 {
				return reader.Size()
			}
			pos, err := reader.Seek(offset, whence)
			if err != nil {
				return int64(ffmpeg.AVErrorEofConst)
			}
			return pos
		},
	)
	if avio == nil {
		t.Fatal("AVIOAllocContext returned nil")
	}
	defer avio.Close()

	fmtCtx := ffmpeg.AVFormatAllocContext()
	if fmtCtx == nil {
		t.Fatal("alloc format context failed")
	}

	fmtCtx.SetPb(avio.Context())
	fmtCtx.SetFlags(fmtCtx.Flags() | ffmpeg.AVFmtFlagCustomIo)

	if _, err := ffmpeg.AVFormatOpenInput(&fmtCtx, nil, nil, nil); err != nil {
		// AVFormatOpenInput frees fmtCtx on failure; the custom AVIO survives.
		t.Fatalf("open input: %v", err)
	}
	defer ffmpeg.AVFormatCloseInput(&fmtCtx)

	if _, err := ffmpeg.AVFormatFindStreamInfo(fmtCtx, nil); err != nil {
		t.Fatalf("find stream info: %v", err)
	}

	if got := fmtCtx.NbStreams(); got < 1 {
		t.Fatalf("expected at least one stream, got %d", got)
	}

	pkt := ffmpeg.AVPacketAlloc()
	if pkt == nil {
		t.Fatal("alloc packet failed")
	}
	defer ffmpeg.AVPacketFree(&pkt)

	if _, err := ffmpeg.AVReadFrame(fmtCtx, pkt); err != nil {
		t.Fatalf("read frame: %v", err)
	}

	if pkt.Size() <= 0 {
		t.Fatalf("expected a non-empty packet, got size %d", pkt.Size())
	}
	ffmpeg.AVPacketUnref(pkt)
}
